<a href="https://colab.research.google.com/github/skssushil/CS208/blob/master/covariance%26corelation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from google.colab import files 
uploaded =files.upload()

Saving AMZN-DUK-KO.csv to AMZN-DUK-KO.csv


In [3]:
import io
data = pd.read_csv(io.BytesIO(uploaded['AMZN-DUK-KO.csv']))
print(data.head(2))
print("The shape of sample data = ", data.shape)

         Date       AMZN        DUK         KO
0  03-01-2007  38.700001  34.971017  17.874906
1  04-01-2007  38.900002  35.044103  17.882263
The shape of sample data =  (2519, 4)


In [4]:
Date = data['Date']
# Droping date parameter
f_data = data.drop("Date",axis=1)
print(f_data.shape)

(2519, 3)


In [5]:
# standrizing the data
from sklearn.preprocessing import StandardScaler
standardized_data = StandardScaler().fit_transform(f_data)
print(standardized_data.shape)

(2519, 3)


In [6]:
#find the co-variance matrix which is : A^T * A/n-1
sample_data = standardized_data
# matrix multiplication using numpy
covar_matrix = np.matmul(sample_data.T , sample_data)
print("co-variance\n",covar_matrix/2518)
print ( "The shape of variance matrix = ", covar_matrix.shape)

co-variance
 [[1.00039714 0.89210261 0.88585829]
 [0.89210261 1.00039714 0.97559994]
 [0.88585829 0.97559994 1.00039714]]
The shape of variance matrix =  (3, 3)


In [7]:
# Geeting correlation matrix
corr = f_data.corr()
print(corr)

          AMZN       DUK        KO
AMZN  1.000000  0.891748  0.885507
DUK   0.891748  1.000000  0.975213
KO    0.885507  0.975213  1.000000
